---
# tasks file for gpu-service

- name: upload service file
  copy:
    src: gpu.service
    dest: /usr/lib/systemd/system/gpu.service

- name: upload startup file
  copy:
    src: start-nvidia
    dest: /usr/bin/start-nvidia
    mode: 755


- name: enable gpu service
  service:
    name: gpu
    enabled: yes

