root = "/data/containerd"
state = "/run/containerd"
oom_score = 0

[grpc]
  address = "/run/containerd/containerd.sock"
  uid = 0
  gid = 0

[debug]
  address = "/run/containerd/debug.sock"
  uid = 0
  gid = 0
  level = "error"

[metrics]
  address = "127.0.0.1:1338"

[cgroup]
  path = ""

[plugins.linux]
	# shim binary name/path
	shim = "{{ bin_dir }}/containerd-shim"
	# runtime binary name/path
	runtime = "{{ bin_dir }}/runc"
	# do not use a shim when starting containers, saves on memory but
	# live restore is not supported
	no_shim = false
	# display shim logs in the containerd daemon's log output
	shim_debug = false
	# do not put the shim in its own mount namespace
	# (this only need to be set on kernel < 3.18)
	shim_no_newns = true
