- hosts: all
  remote_user: root
  # serial: 1
  max_fail_percentage: 0
  gather_facts: False 
  become: true
  become_method: sudo
  roles:
    - ubuntu-packages
    - sys-local-config
    #- { role: ntpd-orphan,  when: single_node is not defined }
    #- preinstall