- hosts: all
  remote_user: root
  # serial: 1
  max_fail_percentage: 0
  gather_facts: False 
  become: true
  become_method: sudo
  roles:
    #- centos-packages
    - sys-local-config
    #- ntpd-orphan
    #- security-policies
    #- reboot
