---
- name: copy and push docker images to harbor
  include: copy_docker_images.yml

 #make sure the directory exist
- name: make sure /tmp/nfs-provisioner/data directory exist on target server
  file:
    path: "/tmp/nfs-provisioner/data"
    state: "directory"
    mode: 0777

- name: copy all yaml files to /tmp/nfs-provisioner/data
  template:
    src: "{{ item.src }}"
    dest: "/tmp/nfs-provisioner/data/{{ item.dest }}"
    mode: 0644
  with_items:
    - {src: deployment.yaml, dest: deployment.yaml}
    - {src: class.yaml, dest: class.yaml}

- name: delete nfs-provisioner app in k8s
  command: kubectl delete -f /tmp/nfs-provisioner/data/{{ item }} -n {{ namespace }}
  with_items:
    - class.yaml
    - deployment.yaml
  when: clean_app == true
  ignore_errors: yes

- name: waite for deleting
  command: sleep 8
  when: clean_app == true

- name: create nfs-provisioner app in k8s
  command: kubectl create -f /tmp/nfs-provisioner/data/{{ item }} -n {{ namespace }}
  with_items:
    - deployment.yaml
    - class.yaml

 #clean up temp files
- name: clean up "/tmp/nfs-provisioner/data"
  file:
    path: "{{ item }}"
    state: "absent"
  with_items:
  - "/tmp/nfs-provisioner/data"