apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appautoscale
  namespace: {{ autoscaler_namespace }}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: appautoscale
    spec:
      containers:
      - name: scale
        image: {{ registry_url }}/{{ scaler_image_url }}
        imagePullPolicy: "Always"
        command:
          - "/scalemanager"
          - "--tokenfilepath=/key/basic_auth.csv"
          - "--certfilepath=/key/server.crt"
          - "--keyfilepath=/key/server.key"
          - "--httpsaddr=127.0.0.1:3078"
          - "--debug=true"
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 300Mi
        volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: sasecret
            readOnly: true
      - name: monitor
        image: {{ registry_url }}/{{ monitor_image_url }}
        imagePullPolicy: "Always"
        command:
          - "/monitor"
          - "--tokenfilepath=/key/basic_auth.csv"
          - "--svcName=appautoscale"
          - "--svcNamespace=kube-system"
          - "--addrInterFaceName=eth0"
          - "--certfilepath=/key/server.crt"
          - "--keyfilepath=/key/server.key"
          - "--scaleserveraddr=https://127.0.0.1:3078"
          - "--scaleserverusername=zhtsC1002"
          - "--scaleserverpassword=zhtsC1002"
          - "--httpsaddr=:3077"
          - "--debug=true"
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 300Mi
        volumeMounts:
          -  mountPath: /var/run/secrets/kubernetes.io/serviceaccount
             name: sasecret
             readOnly: true
      volumes: 
        - name: sasecret
          secret:
            defaultMode: 420
            secretName: {{ token_name.stdout }}