apiVersion: v1
kind: Service
metadata:
  name: appautoscale
  namespace: {{ autoscaler_namespace }}
spec:
  ports:
  - name: http
    port: 80
    nodePort: 29106
    protocol: TCP
    targetPort: 3077
  selector:
    app: appautoscale
  type: NodePort
