---
# tasks file for ingress
- include: fetch_images.yml

- name: create directory to store k8s deployment file
  file: path=/k8s/app/ingress state=directory

- name: set k8s deploy files
  set_fact:
    k8s_deploy_files:
      - {src: default-http-backend-dp.j2 , dst: default-http-backend-dp.json }
      - {src: default-http-backend-svc.j2 , dst: default-http-backend-svc.json }
      - {src: nginx-ingress-controller-dp.j2 , dst: nginx-ingress-controller-dp.json }
      - {src: nginx-ingress-controller-svc.j2 , dst: nginx-ingress-controller-svc.json }
    k8s_config_map:
      - {src: kubeconfig-cm.yaml , dst: kubeconfig-cm.yaml }
      - {src: nginx-default-config-cm.yaml , dst: nginx-default-config-cm.yaml }
      - {src: nginx-ingress-class-cm.yaml , dst: nginx-ingress-class-cm.yaml }

- name: generate k8s deploy files
  template:
    src: "{{ item.src }}"
    dest: "/k8s/app/ingress/{{ item.dst }}"
  with_items:
    - "{{ k8s_deploy_files }}"
    - "{{ k8s_config_map }}"

- name: create dns and ingress controller
  command: kubectl apply -f /k8s/app/ingress

