- name: create /monitor
  file: path=/monitor state=directory

# - name: copy images
#   copy:
#     src: "../files/images/monitor/{{ item.src }}"
#     dest: "{{ item.dest }}"
#   with_items:
#     - {src: archive-server.tar, dest: /monitor}

# - name: load docker images
#   command: docker load -i /monitor/{{ item }}
#   with_items:
#     - archive-server.tar

# - name: push image to registry
#   command: "{{ item }}"
#   with_items:
#     - echo "nonsense" | docker login -uadmin -p{{ harbor_admin_password }} {{ registry_url }}
#     - docker push {{ registry_url }}/{{monitor_log_archive_server_images}}

- name: copy files
  template:
    src: "templates/{{item.src}}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: enn-monitor-log-archive-server-svc.yml, dest: /monitor}
    - {src: enn-monitor-log-archive-server-rc.yml, dest: /monitor}

- name: create security
  command: ennctl create -a {{ monitor_log_app }} -f /monitor/{{ item }}
  with_items:
   - enn-monitor-log-archive-server-svc.yml
   - enn-monitor-log-archive-server-rc.yml
