apiVersion: v1
kind: Service
metadata:
    name: enn-monitor-config-service-web
    labels:
        name: enn-monitor-config-service-web
    namespace: {{ monitor_ns_monitor_application }}
spec:
    type: NodePort
    ports:
        -
            protocol: TCP
            targetPort: 8080
            port: 8080
            nodePort: {{ monitor_config_service_web_externport }}
    selector:
        name: enn-monitor-config-service-web

