apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: enn-monitor-config-service-server
    labels:
        name: enn-monitor-config-service-server
    namespace: {{ monitor_ns_monitor_application }}
spec:
    replicas: {{ monitor_config_service_server_num }}
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 0
    template:
        metadata:
            labels:
                name: enn-monitor-config-service-server
        spec:
            containers:
                -
                    name: enn-monitor-config-service-server
                    image: {{ registry_url }}/{{ monitor_config_service_server_image }}
                    imagePullPolicy: Always
                    resources:
                        requests:
                            memory: {{ monitor_config_service_server_memory_request }}
                            cpu: {{ monitor_config_service_server_cpu_request }}
                        limits:
                            memory: {{ monitor_config_service_server_memory_limit }}
                            cpu: {{ monitor_config_service_server_cpu_limit }}
                    ports:
                        -
                            protocol: TCP
                            containerPort: {{ monitor_config_service_server_listenport }}
                    env:
                        -
                            name: NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -
                            name: PODNAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.name
                        -
                            name: APPNAME
                            value: enn-monitor-config-service-server
                        -
                            name: LOGPATTERN
                            value: '^(?<dateTime>[\d\-]+[\s]+[\d\:\.]+)[\s]*\[(?<threadName>[^\]\s]*)\][\s]*(?<logLevel>[^\s]*)[\s]*(?<position>[^\s]*)[\s\-]*\[(?<traceId>[^\]]*)\][\s\-]*\[(?<parentPod>[^\]]*)\][\s\-]*(?<log>.*)$'
                        -
                            name: LOGASSEMBLE
                            value: '%logLevel%,%position%,%log%,%dateTime%,%traceId%,%parentPod%,%threadName%'
                    command:
                        - "java"
                        - "-cp"
                        - "/opt/enn-monitor-config-service-server.jar"
                        - "enn.monitor.config.server.EnnMonitorConfigServer"
                        - "--workThreadNum"
                        - "16"
                        - "--listen_port"
                        - "{{ monitor_config_service_server_listenport }}"
                        - "--mongoUrl"
                        - "mongodb://{{monitor_mongo_svr}}.monitor-essential-service:{{monitor_mongo_port}}/EnnMonitorConfigService"
                        - "--dbName"
                        - "EnnMonitorConfigService"
                        - "--token"
                        - "{{ monitor_config_service_server_token }}"
                        - "--enable_metrics"
                        - "--gateway_server"
                        - "{{monitor_security_gateway_server_servername}}"
                        - "--gatewayPort"
                        - "{{monitor_security_gateway_server_listenport}}"
