apiVersion: v1
kind: PersistentVolume
metadata: 
  name: system-tools-ldapdata-pv
spec:
  accessModes:
  - ReadWriteMany
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-05c23119d7ba9cc67
  capacity:
    storage: 1Gi