---
# defaults file for app
kubedns_image: "127.0.0.1:30100/library/kube-dns:v1.14.4"
dnsmasq_image: "127.0.0.1:30100/google_containers/kube-dnsmasq-amd64:1.3"
exechealthz_image: "127.0.0.1:30100/google_containers/exechealthz-amd64:1.1"
