---
- hosts: all
  remote_user: root
  # serial: 1
  max_fail_percentage: 0
  gather_facts: False 
  become: true
  become_method: sudo
  roles:
    - special-storage-setup
    - rootca
    - { role: bashrc, become: false }
    - { role: etcd3, when: inventory_hostname in etcd_init_servers }
    - { role: etcd3-flannel, when: (inventory_hostname in flannel_etcd_list) and (flannel_etcd_list != etcd_init_servers) }
    - { role:  flannel-backend-setup, when: inventory_hostname == flannel_etcd_list.0 }
    - flannel
    - docker-ce
    - log-cleanup
    - kubeconfig
    - { role:  k8s-apiserver, when: inventory_hostname in master_list }
    - apiserver-haproxy
    - kubectl
    - { role: k8s-controller-manager, when: inventory_hostname in master_list }
    - { role: k8s-scheduler, when: inventory_hostname in master_list }
    - k8s-proxy
    - k8s-kubelet
    - { role: keepalived, when: inventory_hostname in hanode_list }
    - dns-images
    - { role: kube-dns, become: false, when: inventory_hostname == master_list.0 }
    - enn-policy
    - ihub
    
