---
- name: mk directory
  file:
    path={{ item }}
    state=directory
  with_items:
    - /{{ workspace }}/images

- name: copy files to remote
  template:
    src: "{{ item }}"
    dest: "/{{ workspace }}"
  with_fileglob:
    - "../templates/*"
