---
- name: Install nessecery packages
  apt:
    name: "{{ item }}"
  with_items:
    - docker.io
    - etcd
    - net-tools
    - xfsprogs
    - ntp
    - curl
    - rsync
    - jq
    - unzip
    - ca-certificates
