---
all:
  vars:
    need_netlogin: True
    ntp_lannet: "10.19.1.1 mask 255.255.0.0"
    ntp_orphan_parents: ["10.19.137.140", "10.19.137.141", "10.19.137.142"]
    ntp_server: "10.36.8.40"
    etcd_init_servers: ["10.19.137.140", "10.19.137.141", "10.19.137.142"]
    master_list: ["10.19.137.140", "10.19.137.141", "10.19.137.142"]
    cluster_ip_range: "10.254.0.0/16"
    flannel_etcd_list: ["10.19.137.149", "10.19.137.150", "10.19.137.151"]
    backend_type: "vxlan-over-hostgw"
    flanneld_subnet: "172.16.0.0/12"
    pause_image: "registry.alauda.cn/googlecontainer/pause-amd64:3.0"
    domain: "enn.cn"
    cluster_name: "shanghai"
    max_pods: 100
    cpu_reserved: 0
    memory_reserved: 0
    kubelet_dir: "/data/kubelet"
    local_repo: "10.19.138.173:8009"
    vip: "10.19.140.200"
    ca_vip: "10.19.140.200"
    hanode_list: ["10.19.140.4", "10.19.140.15"]
    etcd_protocol: "http"
    flanneld_subnetlen: 20
  children:
    coreos:
      vars:
        ansible_ssh_user: core
        ansible_python_interpreter: "/home/core/bin/python"
        bin_dir: "/opt/bin"
        cgroup_driver: "cgroupfs"
        osissue: "coreos"
      hosts:
        10.19.137.140:
          badnetworks: ["external0"]
        10.19.137.141:
          badnetworks: ["external0"]
        10.19.137.142:
        10.19.137.143:
        10.19.137.144:
        10.19.137.145:
        10.19.137.146:
        10.19.137.151:
          gpu: 2
        10.19.137.152:
        10.19.137.153:
          badnetworks: ['enp0s31f6']
        10.19.137.154:
          gpu: 1
          badnetworks: ['external0']
        10.19.137.156:
          gpu: 2
        10.19.137.157:
          gpu: 1
        10.19.137.158:
          gpu: 1
        10.19.137.159:
          gpu: 1
        10.19.140.4:
          need_netlogin: False
        10.19.140.7:
          need_netlogin: False 
        10.19.140.9:
          need_netlogin: False 
        10.19.140.12:
          need_netlogin: False
        10.19.140.15:
          need_netlogin: False
    centos:
      vars:
        ansible_ssh_user: root
        bin_dir: "/usr/bin"
        cgroup_driver: "cgroupfs"
        osissue: "centos"
        kernel_version: "kernel-ml"
      hosts:
        10.19.137.149:
          gpu: 2
        10.19.137.150:
          gpu: 2
        10.19.137.147:
          gpu: 2
        10.19.137.148:
          gpu: 2


