---
# vars file for keystone

# NodePort
console_node_port: 29000
gateway_http_node_port: 29002
gateway_https_node_port: 29001
terminal_node_port: 29003
doc_node_port: 29004
pmd_node_port: 29005
harbor_node_port: 29006
es_node_port: 29009
rabbitmq_node_port: 29104
open_tsdb_node_port: 29430
ldap_node_port: 29015

# Docker
docker_user: admin
registry_url: 127.0.0.1:{{ harbor_node_port }}

ldap_url: "{{ ca_vip }}:{{ ldap_node_port }}"
