---
- name: make sure /mnt/nfs directory exist on target server
  file:
    path: "/mnt/nfs"
    state: "directory"
    mode: 0777

# mount -t nfs 398de48d04-qar32.cn-shanghai.nas.aliyuncs.com:/ /mnt/nfs/
- name: mount nfs to local path /mnt/nfs
  mount:
    path: /mnt/nfs
    src: "{{ nfs_host }}:{{ nfs_path }}"
    fstype: nfs
    state: mounted

- name: make sure all need  directory exist on target server
  file:
    path: "/mnt/nfs/k8s/system-tools/{{ item }}"
    state: "directory"
    mode: 0777
  with_items:
  - harbor-db
  - harbor-redis
  - harbor-registry

- name: umount /mnt/nfs
  mount:
    path: /mnt/nfs
    state: unmounted
