---
- hosts: all
  remote_user: root
  max_fail_percentage: 0
  gather_facts: False
  become: true
  become_method: sudo
  roles:
    - role: bigdata-image 
      when: inventory_hostname in master_list[0]
