apiVersion: v1
kind: List 
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: mt-console
      namespace: {{ namespace }}
    labels:
      app: mt-console
    spec:
      type: NodePort
      ports:
        - name: web
          nodePort: 29311
          port: 8006
          protocol: TCP
          targetPort: 8006
      selector:
        tier: frontend
        app: mt-console
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: mt-console
      namespace: {{ namespace }}
    labels:
      tier: frontend 
      app: mt-console 
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            tier: frontend 
            app: mt-console        
            X_NAMESPACE: {{ namespace }}
        spec:
          containers:
          - image: {{ registry_url }}/monitor/mt-console:{{ image_version }}
            env:
              - name: "MONITOR_URL"
                value: http://{{ ca_vip }}:29313/api/v1
            name: mt-console
            ports:
            - containerPort: 8006
              name: web
              protocol: TCP
            resources:
              requests:
                memory: {{ fe_mem_req }}
                cpu: {{ fe_cpu_req }}
              limits:
                memory: {{ fe_mem_limit }}
                cpu: {{ fe_cpu_limit }}
          volumes:
          - name: mt-console
            persistentVolumeClaim:
              claimName: mt-console
  - apiVersion: v1
    kind: Storage
    metadata:
      name: mt-console
      namespace: {{ namespace }}
    spec:
      type: {{ 'NFS' if (storage_type == 'nfs') else 'RBD' }}
      accessModes: ReadWriteMany
      persisted: true
      unshared: true
      resources:
        requests:
          storage: {{ mt_console_disk_req }}        