---
- hosts: all
  remote_user: root
  max_fail_percentage: 0
  gather_facts: False
  become: true
  become_method: sudo
  roles:
    - role: storage-setup
      when: inventory_hostname in master_list[0]
    - role: jsonnet
      when: inventory_hostname in master_list[0]
    - role: create-console
      when: inventory_hostname in master_list[0]
    - role: convert-console
      when: inventory_hostname in master_list[0]
    - role: ennctl
      when: inventory_hostname in master_list[0]
