registry_url: 127.0.0.1:29006
monitor_mongo_image: monitor/mongo-3.4:0.1.0.RELEASE
mysql_image_version: helium-1.3.0-snapshot

monitor_mongo_cpu_request: 0.3
monitor_mongo_cpu_limit: 0.3
monitor_mongo_memory_request: 500Mi
monitor_mongo_memory_limit: 500Mi

# mysql
mysql_image: "{{ registry_url }}/tools/dep-centos7-mysql-5.7.18:{{ mysql_image_version }}"
mysql_instancecount: 1
mysql_datapvcstoragesize: "5Gi"
mydql_requestcpu: "500m"
mysql_requestmem: "500Mi"
mysql_limitcpu: "1"
mysql_limitmem: "2000Mi"
mysql_amah_image: "{{ registry_url }}/tools/amah-mysql-5.7.18:{{ mysql_image_version }}"


monitor_ns_monitor_application: monitor-application
monitor_ns_monitor_essential_service: monitor-essential-service

monitor_mongo_app: mongo
monitor_mongo_svr: mongo
monitor_mongo_port: 27017

monitor_mysql_app: monitor-mysql


ceph_enabled: "true"
nfs_enabled: "false"
storage_type: "HostPath"

