apiVersion: v1
kind: Service
metadata:
    name: kibana-logging
    namespace: {{ monitor_ns_monitor_application }}
    labels:
        name: kibana-logging
spec:
    type: NodePort
    ports:
        -
            protocol: TCP
            targetPort: {{monitor_kibana_export_port}}
            port: {{monitor_kibana_export_port}}
            nodePort: {{monitor_kibana_export_port}}
    selector:
        name: kibana-logging
