---
apiVersion: v1
kind: List
items:
 - apiVersion: v1
   kind: Service
   metadata:
     name: msc-console
     namespace: {{ monitor_prometheus_namespace }}
   selector:
      tier: frontend
      app: msc-console
   spec:
     type: NodePort
     ports:
       - name: web
         nodePort: 29312
         port: 8006
         protocol: TCP
         targetPort: 8006
     selector:
       tier: frontend
       app: msc-console
 - apiVersion: extensions/v1beta1
   kind: Deployment
   metadata:
     name: msc-console
     namespace: {{ monitor_prometheus_namespace }}
     labels:
       tier: frontend
       app: msc-console
   spec:
     replicas: 1
     template:
       metadata:
         labels:
           tier: frontend
           app: msc-console
           X_NAMESPACE: {{ monitor_prometheus_namespace }}
       spec:
         containers:
         - image: {{ registry_url }}/monitor/msc-console:{{ monitor_release_verison }}
           env:
             - name: "MONITOR_URL"
               value: http://{{ v_ip }}:29308/api/v1
           name: msc-console
           ports:
           - containerPort: 8006
             name: web
             protocol: TCP
           resources:
             requests:
               memory: {{ msc_fe_mem_req }}
               cpu: {{ msc_fe_cpu_req }}
             limits:
               memory: {{ msc_fe_mem_limit }}
               cpu: {{ msc_fe_cpu_limit }}
         volumes:
         - name: msc-console
           persistentVolumeClaim:
             claimName: msc-console
 - apiVersion: v1
   kind: Storage
   metadata:
      name: msc-console
      namespace: {{ monitor_prometheus_namespace }}
   spec:
      type: {{ 'NFS' if (storage_type == 'nfs') else 'HostPath' }}
      accessModes: ReadWriteOnce
      persisted: true
      unshared: true
      resources:
        requests:
          storage: {{ msc_console_disk_req }}          

