---
# vars file for autoscalemanager

nsnodeselector_image_url: library/enndata-scheduler:v0.1.0

##The initial password of Harbor admin, only works for the first time when Harbor starts.
#It has no effect after the first launch of Harbor.
#Change the admin password from UI after launching Harbor.
harbor_admin_password: admin
registry_url: 127.0.0.1:29006
