apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig
  namespace: kube-system
data:
  kubeconfig: |-
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        insecure-skip-tls-verify: true
        server: {{ master_addr }}
      name: enn-cluster
    contexts:
    - context:
        cluster: enn-cluster
        user: kube-node
      name: node-context
    current-context: node-context
    users:
    - name: kube-node
      user:
        password: {{ admin_password }}
        username: {{ admin_username }}
