---
# tasks file for nfs-lib
- name: install nfs-lib on centos
  yum:
    name: nfs-utils
    state: installed
  when: ansible_distribution == "CentOS"

- name: install nfs-lib on ubuntu or debian
  apt:
    name: nfs-common
    state: latest
  when: ansible_distribution == "Ubuntu"