---
# tasks file for bashrc
- name: Set etcd client
  lineinfile:
    dest: /root/.bashrc
    line: "{{ item }}"
  with_items:
    - "export ETCDCTL_CA_FILE=/etc/ssl/ca.pem"
    - "export ETCDCTL_CERT_FILE=/etc/ssl/etcd/etcd-admin.pem"
    - "export ETCDCTL_KEY_FILE=/etc/ssl/etcd/etcd-admin-key.pem"
