---
# tasks file for convert-console
- name: move gateway deployment to app
  uri:
    url: http://{{ master_list[0] }}:{{ node_port.gateway_http }}/gw/in/api/v1/namespaces/{{ namespace.system_tools }}/deployment/{{ item }}/add_to_app/gateway
    method: POST
    timeout: 300
    validate_certs: no
    headers:
      Content-Type: "application/json"
      x-gw-user-id: admin
      x-gw-req-id: console
      Authorization: "Bearer {{ access_token }}"
  with_items:
    - "{{ gateway_deployments }}"
  register: result
  until: result.status == 200 or result.status == 201 or result.status == 400
  retries: 10
  delay: 30

- name: move gateway service to app
  uri:
    url: http://{{ master_list[0] }}:{{ node_port.gateway_http }}/gw/in/api/v1/namespaces/{{ namespace.system_tools }}/service/{{ item }}/add_to_app/gateway
    method: POST
    timeout: 300
    validate_certs: no
    headers:
      Content-Type: "application/json"
      x-gw-user-id: admin
      x-gw-req-id: console
      Authorization: "Bearer {{ access_token }}"
  with_items:
    - "{{ gateway_services }}"
  register: result
  until: result.status == 200 or result.status == 201 or result.status == 400
  retries: 10
  delay: 30
