apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: enn-monitor-security-gateway-web
    labels:
        name: enn-monitor-security-gateway-web
    namespace: {{ monitor_ns_monitor_application }}
spec:
    replicas: {{ monitor_security_gateway_web_num }}
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 0
    template:
        metadata:
            labels:
                name: enn-monitor-security-gateway-web
        spec:
            containers:
                -
                    name: enn-monitor-security-gateway-web
                    image: {{ registry_url }}/{{ monitor_security_gateway_web_image }}
                    resources:
                        requests:
                            memory: {{ monitor_security_gateway_web_memory_request }}
                            cpu: {{ monitor_security_gateway_web_cpu_request }}
                        limits:
                            memory: {{ monitor_security_gateway_web_memory_limit }}
                            cpu: {{ monitor_security_gateway_web_cpu_limit }}
                    ports:
                        -
                            protocol: TCP
                            containerPort: {{ monitor_security_gateway_web_listenport }}
                    env:
                        -
                            name: NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -
                            name: PODNAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.name
                        -
                            name: APPNAME
                            value: enn-monitor-security-gateway-web
                        -
                            name: LOGPATTERN
                            value: '^(?<dateTime>[\d\-]+[\s]+[\d\:\.]+)[\s]*\[(?<threadName>[^\]\s]*)\][\s]*(?<logLevel>[^\s]*)[\s]*(?<position>[^\s]*)[\s\-]*\[(?<traceId>[^\]]*)\][\s\-]*\[(?<parentPod>[^\]]*)\][\s\-]*(?<log>.*)$'
                        -
                            name: LOGASSEMBLE
                            value: '%logLevel%,%position%,%log%,%dateTime%,%traceId%,%parentPod%,%threadName%'
                    command:
                        - "java"
                        - "-cp"
                        - "/opt/enn-monitor-security-gateway-web.jar"
                        - "enn.monitor.security.gateway.web.EnnMonitorSecurityGatewayServer"
                        - "--listen_port"
                        - "{{ monitor_security_gateway_web_listenport }}"
                        - "--enable_metrics"
                        - "--token"
                        - "micklongen-gateway-server"
                        - "--gateway_server"
                        - "{{ monitor_security_gateway_server_servername }}"
                        - "--gatewayPort"
                        - "{{ monitor_security_gateway_server_listenport }}"
