apiVersion: v1
kind: Service
metadata:
    name: enn-monitor-security-gateway-server
    labels:
        name: enn-monitor-security-gateway-server
    namespace: {{ monitor_ns_monitor_application }}
spec:
    type: NodePort
    ports:
        -
            protocol: TCP
            name: p1
            targetPort: {{ monitor_security_gateway_server_listenport }}
            port: {{ monitor_security_gateway_server_listenport }}
            nodePort: {{ monitor_security_gateway_server_externport }}
    selector:
        name: enn-monitor-security-gateway-server

