apiVersion: v1
kind: Service
metadata:
    name: enn-monitor-security-config-server
    labels:
        name: enn-monitor-security-config-server
    namespace: {{ monitor_ns_monitor_application }}
spec:
    type: ClusterIP
    ports:
        -
            protocol: TCP
            targetPort: {{ monitor_security_config_server_listenport }}
            port: {{ monitor_security_config_server_listenport }}
    selector:
        name: enn-monitor-security-config-server
