apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-properties-gateway-server
  namespace: {{ monitor_ns_monitor_application }}
data:
  monitor.properties: |-
    trace.switch=on
    trace.bizLine=Monitor
    trace.service=Security-gateway-server

    gateway.grpcHost=enn-monitor-security-gateway-server.monitor-application
    gateway.grpcPort=10000
    gateway.token=EDAE3C40B04DACEDCA797921C91DEB81

    metric.switch=on
    metric.frequency=1
