apiVersion: v1
kind: Service
metadata:
    name: enn-monitor-security-gateway-web
    labels:
        name: enn-monitor-security-gateway-web
    namespace: {{ monitor_ns_monitor_application }}
spec:
    type: NodePort
    ports:
        -
            protocol: TCP
            name: p1
            targetPort: {{ monitor_security_gateway_web_listenport }}
            port: {{ monitor_security_gateway_web_listenport }}
            nodePort: {{ monitor_security_gateway_web_externport }}
    selector:
        name: enn-monitor-security-gateway-web

