apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitor-streaming-metric
  namespace: {{ namespace }}
  labels:
    name: monitor-streaming-metric
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: monitor-streaming-metric
    spec:
      containers:
        - name: monitor-streaming-metric
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: {{ streaming_request_memory }}
              cpu: {{ streaming_request_cpu }}
            limits:
              memory: {{ streaming_limit_memory }}
              cpu: {{ streaming_limit_cpu }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: "METANAME"
              value: "monitor-streaming-metric"
            - name: SPARK_MASTER
              value: spark://pre1-master1.monitor-essential-service:7077,pre1-master2.monitor-essential-service:7077,pre1-master3.monitor-essential-service:7077
            - name: TOTAL_CORES
              value: "3"
            - name: EXECUTOR_MEM
              value: 1000m
            - name: EXECUTOR_CORES
              value: "1"
            - name: MAX_RATE
              value: "1000"
            - name: WORKSPACE
              value: /opt/workspace
            - name: JOB_JAR
              value: streaming-metric.jar
            - name: MAIN_CLASS
              value: enn.monitor.metric.kubelet.streaming.Collector
            - name: KAFKA
              value: pre1-kafka1.monitor-essential-service:9092,pre1-kafka2.monitor-essential-service:9092,pre1-kafka3.monitor-essential-service:9092
            - name: PROM_PUSH
              value: prometheus-pushgateway1.monitor-application:9091
            - name: GROUP_ID
              value: monitor-streaming
            - name: TOPIC_NAME
              value: k8s-kubelet
            - name: ASYNC
              value: "off"
            - name: RDD_PARTITION
              value: "0"
            - name: SPARK_BATCH
              value: "3"
            - name: APIUSER
              value: {{ admin_username }}
            - name: APIPASS
              value: {{ admin_password }}
            - name: APISERVER
              value: "kubernetes.default:443"
            - name: OPENTSDB
              value: pre1-opentsdb.monitor-essential-service:4242
          image: {{ registry_url }}/monitor/monitor-streaming-jobs:{{ streaming_image_version }}
          ports:
            - containerPort: 4040
          command:
            - /opt/workspace/start-streaming-metric.sh
