---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitor-streaming-app
  namespace: {{ namespace }}
  labels:
    name: monitor-streaming-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: monitor-streaming-app
    spec:
      containers:
        - name: monitor-streaming-app
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: {{ streaming_request_memory }}
              cpu: {{ streaming_request_cpu }}
            limits:
              memory: {{ streaming_limit_memory }}
              cpu: {{ streaming_limit_cpu }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: "METANAME"
              value: "monitor-streaming-app"
            - name: WORKSPACE
              value: "/opt/workspace"
            - name: JOB_JAR
              value: "streaming-app.jar"
            - name: SPARK_MASTER
              value: spark://pre1-master1.monitor-essential-service:7077,pre1-master2.monitor-essential-service:7077,pre1-master3.monitor-essential-service:7077
            - name: MAIN_CLASS
              value: enn.monitor.metric.app.streaming.Collector
            - name: TOTAL_CORES
              value: "2"
            - name: EXECUTOR_MEM
              value: "1g"
            - name: EXECUTOR_CORES
              value: "1"
            - name: MAX_RATE
              value: "500"
            - name: KAFKA
              value: pre1-kafka1.monitor-essential-service:9092,pre1-kafka2.monitor-essential-service:9092,pre1-kafka3.monitor-essential-service:9092
            - name: TOPIC_NAME
              value: monitor-app
            - name: GROUP_ID
              value: monitor-streaming
            - name: OPENTSDB
              value: pre1-opentsdb.monitor-essential-service:4242
          image: {{ registry_url }}/monitor/monitor-streaming-jobs:{{ streaming_image_version }}
          ports:
            - containerPort: 4040
          command:
            - /opt/workspace/start-streaming-app.sh
