---
- name: Get the existing groups
  ali_security_group_facts:
    region: '{{alicloud_region}}'
    group_name: '{{ group_name }}'
    filters: 
      vpc_id: '{{vpcs.vpcs.0.id}}'
  register: sgs

- name: Creating an ECS instance
  ali_instance:
    alicloud_region: '{{ alicloud_region }}'
    alicloud_zone: '{{ alicloud_zone }}'
    image: '{{ image_id }}'
    type: '{{ instance_type }}'
    instance_name: '{{ instance_name }}'
    description: '{{ instance_description }}'
#    host_name: '{{ host_name }}'
#    password: '{{ password }}'
    key_name: '{{ key_name }}'

    allocate_public_ip: '{{ allocate_public_ip }}'
    internet_charge_type: '{{ internet_charge_type }}'
    max_bandwidth_in: '{{ max_bandwidth_in }}'
    max_bandwidth_out: '{{ max_bandwidth_out }}'
    instance_tags: '{{ instance_tags }}'

    security_groups: ['{{ sgs.groups.0.id }}']
    vswitch_id: '{{ vswitch.vswitch.id }}'

    system_disk_category: '{{ system_disk_category }}'
    system_disk_size: '{{ system_disk_size }}'

    state: 'present'
    count: '{{ number_of_instances }}'
  #when: group.group
  register: instance

- name: Create /dev/sdb disk and attach it to instance
  ali_disk:
    alicloud_region: '{{ alicloud_region }}'
    alicloud_zone: '{{ alicloud_zone }}'
    disk_name: '{{ disk_name }}-sdb-{{ item.id }}'
    disk_category: '{{ disk_category }}'
    description: '{{ disk_description }}'
    size: '{{ data_disk_sdb_size }}'
    disk_tags: '{{ disk_tags }}'
    instance_id: '{{ item.id }}'
    delete_with_instance: '{{ delete_with_instance }}'
  with_items: '{{ instance.instances }}'

- name: Create /dev/sdc disk and attach it to instance
  ali_disk:
    alicloud_region: '{{ alicloud_region }}'
    alicloud_zone: '{{ alicloud_zone }}'
    disk_name: '{{ disk_name }}-sdc-{{ item.id }}'
    disk_category: '{{ disk_category }}'
    description: '{{ disk_description }}'
    size: '{{ data_disk_sdc_size }}'
    disk_tags: '{{ disk_tags }}'
    instance_id: '{{ item.id }}'
    delete_with_instance: '{{ delete_with_instance }}'
  with_items: '{{ instance.instances }}'

- name: reboot instance forcibly
  ali_instance:
    alicloud_region: '{{ alicloud_region }}'
    instance_name: '{{ item.instance_name }}'
    state: 'running'
    force: '{{ force }}'
  with_items: '{{ instance.instances }}'

- name: Wait for the instances to boot by checking the ssh port
  wait_for: host={{item.private_ip_address}} port=22 delay=15 timeout=300 state=started
  with_items: "{{ instance.instances }}"

